---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus-nginxlog-exporter.fullname" . }}
  namespace: {{ include "prometheus-nginxlog-exporter.namespace" . }}
  labels:
    {{- include "prometheus-nginxlog-exporter.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 4040
      targetPort: http
      protocol: TCP
      appProtocol: http
      name: http
  selector:
    {{- include "prometheus-nginxlog-exporter.selectorLabels" . | nindent 4 }}
