{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
metadata:
  name: {{ include "prometheus-nginxlog-exporter.serviceAccountName" . }}
  namespace: {{ include "prometheus-nginxlog-exporter.namespace" . }}
  labels:
    {{- include "prometheus-nginxlog-exporter.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | tpl . | nindent 4 }}
  {{- end }}
{{- end }}
