{{ if not .Values.existingConfigSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "keycloak-config-cli.fullname" . }}-config-realms
  labels:
  {{- include "keycloak-config-cli.labels" . | nindent 4 }}
stringData:
  {{- range $name, $config := .Values.config }}
    {{- if hasKey $config "file" }}
  {{ $name }}.json: |
    {{ tpl ($.Files.Get $config.file) $ | indent 4}}
    {{- else if hasKey $config "inline" }}
      {{- if kindIs "string" $config.inline }}
  {{ $name }}.json: |
    {{ tpl $config.inline $ | indent 4}}
      {{- else }}
  {{ $name }}.json: |
    {{ tpl (toJson $config.inline) $ | indent 4 }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
