name: Sync Pages

permissions: {}

on:
  push:
    branches:
      - 'main'
    paths:
      - 'README.md'
      - 'changelog/index.html'
      - 'docs/**'
      - '.github/workflows/sync-pages.yaml'

jobs:
  build:
    permissions:
      contents: write # for git push

    runs-on: ubuntu-24.04
    steps:
      - name: Checkout main branch
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          path: main

      - name: Checkout gh-pages branch
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: true
          ref: gh-pages
          path: gh-pages

      - name: Copy files and push to gh-pages
        working-directory: gh-pages
        run: |
          cp -a ../main/README.md .
          cp -a ../main/changelog .
          cp -a ../main/docs .

          rm -rf ./changelog/README.md ./docs/README.md

          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add README.md changelog docs
          git commit --signoff -m "Sync from main"
          git push
